[package]
name = "sdf"
version = "0.1.0"
authors = ["Elias Eskelinen <elias.eskelinen@pm.me>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.23.12"
chrono = "0.4.19"
